name: AWS OIDC Deployment

on:
  push:
    branches:
      - main

# Required permissions for OIDC authentication
permissions:
  id-token: write # This is required for requesting the JWT token from GitHub
  contents: read # This is required for actions/checkout

jobs:
  DeployToAWS:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::277361136766:role/my-github-actions-role
          aws-region: us-east-1 # Replace with your target region

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity
